# name: Example
# on: workflow_dispatch
# jobs:
#   example:
#     runs-on: ubuntu-latest
#     steps:
#       - id: checkout
#         run: |
#           git clone https://projects.blender.org/blender/blender --filter=blob:none --single-branch --branch=main
#           cd blender
#           git fetch --tags
#           cd ..
#       - id: semver
#         uses: BBBrassil/action-semver@main
#         with:
#           workspace: "blender"
#           prefix: "v"
#       - id: output
#         run: |
#           echo "core:        '${{ steps.semver.outputs.core }}'"
#           echo "pre-release: '${{ steps.semver.outputs.pre-release }}'"
#           echo "build:       '${{ steps.semver.outputs.build }}'"
name: Example
on: workflow_dispatch
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "sschmid/Entitas"
          fetch-depth: 0
          sparse-checkout: .github
          path: "entitas"
      - uses: actions/checkout@v4
        with:
          repository: "SanderMertens/flecs"
          fetch-depth: 0
          sparse-checkout: .github
          path: "flecs"
      - id: semver-entitas
        uses: BBBrassil/action-semver@main
        with:
          workspace: "entitas"
      - id: semver-flecs
        uses: BBBrassil/action-semver@main
        with:
          workspace: "flecs"
          prefix: "v"
      - run: |
          echo "Entitas: ${{ steps.semver-entitas.outputs.core }}'"
          echo "Flecs:   ${{ steps.semver-flecs.outputs.core }}'"