# name: Example
# on: workflow_dispatch
# jobs:
#   example:
#     runs-on: ubuntu-latest
#     steps:
#       - id: checkout
#         run: |
#           git clone https://projects.blender.org/blender/blender --filter=blob:none --single-branch --branch=main
#           cd blender
#           git fetch --tags
#           cd ..
#       - id: semver
#         uses: BBBrassil/action-semver@main
#         with:
#           workspace: "blender"
#           prefix: "v"
#       - id: output
#         run: |
#           echo "core:        '${{ steps.semver.outputs.core }}'"
#           echo "pre-release: '${{ steps.semver.outputs.pre-release }}'"
#           echo "build:       '${{ steps.semver.outputs.build }}'"
name: Example
on: workflow_dispatch
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "facebook/react"
          fetch-depth: 0
          sparse-checkout: .github
          path: "react"
      - uses: actions/checkout@v4
        with:
          repository: "electron/electron"
          fetch-depth: 0
          sparse-checkout: .github
          path: "electron"
      - id: semver-react
        uses: BBBrassil/action-semver@main
        with:
          workspace: "react"
          prefix: "v"        
      - id: semver-electron
        uses: BBBrassil/action-semver@main
        with:
          workspace: "electron"
          prefix: "v"
      - run: |
          echo "React:    ${{ steps.semver-react.outputs.core }}'"
          echo "Electron: ${{ steps.semver-react.outputs.core }}'"