name: semver

on:
  workflow_dispatch:
    inputs:
      repository:
        type: string
        required: true
      ref:
        type: string
        required: false
      type:
        type: choice
        options:
        - "major"
        - "minor"
        - "patch"
        required: true
      prerelease:
        type: string
        required: false
      metadata:
        type: string
        required: false

concurrency:
  group: semver
  cancel-in-progress: false

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      current: ${{ steps.get_current_version.outputs.current }}
      next: ${{ steps.get_next_version.outputs.next }}
    steps:
    - name: Checkout semver
      id: checkout_semver
      uses: actions/checkout@v4
      with:
        repository: BBBrassil/action-semver
        path: "semver"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout Repo
      id: checkout_repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: "repo"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get Current Version
      id: get_current_version
      run: |
          cd repo
          echo "current=$(git tag --merged HEAD --sort=-version:refname | head -n 1)\n" >> $GITHUB_OUTPUT
          cd ..
    - name: Get Next Version
      id: get_next_version
      run: |
          cd repo
          current=${{ steps.get_current_version.outputs.current }}
          type=${{ inputs.type }}
          prerelease=${{ inputs.prerelease }}
          metadata=${{ inputs.metadata }}
          delta=$(echo $(
            if [[ $prerelease != "" && $metadata != "" ]]; then
              echo "$type-$prerelease+$metadata"
            elif [[ $prerelease != "" ]]; then
              echo "$type-$prerelease"
            elif [[ $metadata != "" ]]; then
              echo "$type+metadata"
            else
              echo "$type"
            fi
          ))
          echo "next=$(bash ../semver/src/semver.sh "$current" $"delta")\n" >> $GITHUB_OUTPUT
          cd ..