name: Test
on:
  workflow_dispatch:
    inputs:
      version-type:
        # Type of semantic version to compute (major, minor, or patch)
        description: "Version Type"
        type: choice
        options:
        - "major"
        - "minor"
        - "patch"
        default: ""
        required: true
      pre-release:
        # Optional pre-release identifier for the next version
        description: "Pre-Release Identifier"
        type: string
        required: false
      build-metadata:
        # Optional build metadata for the next version
        description: Build Metadata
        type: string
        required: false
      tag-prefix:
        # Identifier which prefixes the semantic version in a tag (e.g. 'v' if 'v1.2.3' is an example of a valid tag)
        description: Tag Prefix
        type: string
        required: false

concurrency:
  group: semver
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: "Checkout"
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        fetch-tags: true
    - id: semver
      name: "SemVer"
      uses: BBBrassil/action-semver@main
      with:
        version-type: ${{ inputs.version-type}}
        pre-release: ${{ inputs.pre-release}}
        build-metadata: ${{ inputs.build-metadata}}
        tag-prefix: ${{ inputs.tag-prefix}}
    - id: output
      name: "Output"
      run: |
        echo "current: ${{ steps.semver.outputs.version.current }}, next: ${{ steps.semver.outputs.version.next }}"